### ISSUE TITLE
Comment for Book + Source

### ISSUE THREAD

**Issue by jeffnyman** [caio-ribeiro-pereira/building-apis-with-nodejs#17]
This is not an issue, per se, but it's unclear where else to publish some ideas.

Chapter 7 is a great addition to the book in terms of taking what went before and then providing authentication. However, in a previous chapter you showed people how to use Postman to test the API.

With the addition of authentication, however, that no longer works. Or, rather, you have to use Postman to authenticate as well by providing an authentication type. That would ideally be a good thing to have at the end of chapter 7 so that people can consistently understand how to interact with the API when there is authentication.

Just a thought.

**Comment by hieudang59** [comment]
Nice idea. The sample don't work when I'm over Authenticating users section

**Comment by caio-ribeiro-pereira** [comment]
@jeffnyman thank you for this feedback, you can easy comment `.all(app.auth.authenticate())` in the routes you wanna test without JWT auth or you can edit the `authenticate()` function to ignore JWT in development environment (but this could causes some issues, because there are queries which uses the logged `user.id`) in `auth.js` anyway you can do something like this:

``` javascript
authenticate: () => {
   if (process.env.NODE_ENV !== 'development') {
       return passport.authenticate("jwt", cfg.jwtSession);
   }
   // ignoring the jwt authentication
   // WARNING this could make happen new issues
   return function(req, res, next) {
        return next();
   }
}
```
