### ISSUE TITLE
Failed at the ntask-api@1.0.0 start script 'babel-node index.js'

### ISSUE THREAD

**Issue by bentzibentz** [caio-ribeiro-pereira/building-apis-with-nodejs#3]
Hi,
first of all, i really like your ebook! It's great!
But i got the same issue as has already been described here ( http://forum.casadocodigo.com.br/t/construindo-apis-rest-com-nodejs-consideracoes-durante-o-estudo/82 ) but my Portuguese is not so good ;).

I also attached my npm-debug.log.

Is it possible that you can explain some tips to solve this problem here?

I would be very grateful.

[npm-debug.txt](https://github.com/caio-ribeiro-pereira/building-apis-with-nodejs/files/191644/npm-debug.txt)

**Comment by caio-ribeiro-pereira** [comment]
Hi, if you have some problems trying to run babel, you can simply use the old version:  

npm install babel@5.8.23 --save
npm install babel-runtime@5.8.25 --save-dev


The english version of my ebook is updated and all issues was solved, take a look: https://leanpub.com/building-apis-with-nodejs

The reason the portuguese version has some issues, is because the release of this book happened the same time a lot of modules update to new versions, and next month I'll update the portuguese version  

Regards,
Caio Ribeiro Pereira
Developer, blogger and writter
About: http://crpwebdev.com
Blog: http://udgwebdev.com
